### ISSUE TITLE
Bug: Chosen folder is ignored

### ISSUE THREAD

**Issue by upekshapriya** [M2000Interpreter/DVmateEn#1]
Instead of the chosen folder the DVgrab default location of the Home folder is used.

**Comment by M2000Interpreter** [comment]
I have to see that also. Thank you.

**Comment by M2000Interpreter** [comment]
I check it and now is working just fine (ubuntu 16.04 - Sony HVR 2000 - HDV format)
(format is taken automatic by the source)

**Comment by upekshapriya** [comment]
Thanks for solving the folder issue, however the format defaults to raw in dvgrab - it'd be good to be able to set it as avi type 1 or type 2
