### ISSUE TITLE
Suggestion: Options for choosing the type of DV file

### ISSUE THREAD

**Issue by upekshapriya** [M2000Interpreter/DVmateEn#2]
It'd be great to be able to set the option to capture with the different DVgrab options DV AVI type 1, DV AVI type 2 and HDV as well as raw DV.

**Comment by M2000Interpreter** [comment]
Ok, I have to look code again, but next week, because I am on vacations now. 
But as I think now the file type for export based on firewire data type, as camcorder send.

**Comment by upekshapriya** [comment]
Thanks for responding - I hope your vacation is good!
However the dvgrab manual offers different formats to record into - see https://linux.die.net/man/1/dvgrab - the default is raw.
