### ISSUE TITLE
Is dvgrab a dependency or is it stored in the app?

### ISSUE THREAD

**Issue by upekshapriya** [M2000Interpreter/DVmateEn#4]
I'm trying to edit the code in order to change the format of the output file to avi. dvgrab has the argument `-f dv1` for this but when I include this it tells me `Unknown file format :  dv1`

https://www.systutorials.com/docs/linux/man/1-dvgrab/

Where is the dvgrab file stored?

**Comment by M2000Interpreter** [comment]
I have dvgrab 3.5-2 (xenial)
Open Synaptic and search for dvgrab to find dependencies 
I never use dvgrab for Dv, but for  HDV.
In the link you place above as I read, dv1 supported.
-f, -format dv1 | dv2 | avi | raw | dif | qt | mov | jpeg | jpg | mpeg2 | hdv
Maybe you tell about filenames, but linux has nothing to do with filenames (only window manager use them)

**Comment by upekshapriya** [comment]
Just to let you know I solved it by making the filename end in .avi and it produced .avi files fine after that 😊

**Comment by M2000Interpreter** [comment]
Ok! I use this program to export to m2t for HDV from my Sony Camera.
